import "@/styles/reset.scss";
import type { AppProps } from "next/app";
import { Noto_Sans_KR } from "next/font/google";
import Head from "next/head";

const font = Noto_Sans_KR({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={font.className}>
        <Component {...pageProps} />
      </div>
    </>
  );
}
